function Chetan() {}
Chetan.prototype.phrases = [ "ah I see",
    "anyhow I think we will deploy the case as is for now and fix this is in future",
    "call USA is good",
    "chatting with DLove",
    "css classes are hyphenated. ",
    "css classes exclusively used for javascript selector purposes are camel case and prefixed with 'js'",
    "default is true",
    "Did that and reverted it back.",
    "dont see any other differences",
    "easy targets",
    "even assuming the url is cached, there is a lot of time spent in parsing json",
    "great.. let me know if you need any help.. I am in a hiding",
    "Hey! I'm feeling good. how are you?",
    "hey, remember the user setup optimization?",
    "hi",
    "hmm",
    "hmm.. does it throw any exceptions?",
    "hmm.. there are couple of options",
    "I am going to use their api to auto-hide Santiago's complaints.",
    "I can't find in the the google code style, but we really like to add curly braces for if, even if it encloses a single statement.",
    "I dont think we need to do that",
    "I like to blame the css guys for all my misery",
    "I talked to Kristian a while ago and we think we should just remove the HSQL thing and show a more meaningful message when that happens",
    "I think I have a patch for it",
    "I took it out.",
    "I'll look at it right away",
    "I'm not sure if thats what you meant",
    "ids should be camel case, ",
    "if it is not express, don't worry about it too much",
    "if it works there, it should work with the app too",
    "if not cached, it will actually make those requests",
    "is there a qa instance where I can see this?",
    "it is never really meant to do that",
    "it is not the most awesome thing out there",
    "it is quite tiny and simple",
    "it is ugly anyway",
    "it is very fast now but there is still some room for improvement",
    "it is weird explaining new guys that we need to run functional tests to run js unit tests",
    "it will probably go away soon",
    "it worked fine during the conference",
    "Just adding a comment there should be sufficient to understand",
    "just to keep in mind I will create a case for future",
    "Let's not use hyphenated file names for javascript. No reason in particular, but we've been using camel-case lately",
    "my opinion is to not fix it",
    "node has jsdom, which is again some sort of hack",
    "not sure, but based on the current experience so far, it would be great if we have...",
    "now I'm \"ok\"",
    "ok, but where do you need to use it?",
    "second option takes some extra work to make it work with functional runner",
    "so",
    "so each dropdown makes its own request for json right?",
    "some of them are same URLs",
    "someone messed up Poland",
    "something using jquery.deferred",
    "sorry got disconnected.. we'll chat later",
    "Thanks for pitching in!",
    "that didn't happen before",
    "that's my question",
    "that's the only suspect code as far as I can tell",
    "The preferred way of creating a new object is '{}'.",
    "there are no events",
    "There isn't anything for user-agent, but maybe add a method and replace all other occurrences?",
    "There won't be an error other than a catastrophic failure ",
    "These were added for server side paging, no longer necessary. Please remove them.",
    "try rhino rather than node easier to use with java",
    "umm.. ok",
    "umm.. yeah it works for pie",
    "wait.. say haha after a minute",
    "we can always add features",
    "We had a similar problem (slow pump) that was solved by running ANALYZE.",
    "we need something that looks at the md5 before making the ajax call and not do it if a call is in progress",
    "we should do the simplest thing possible",
    "We talked about this, but sending this so others may have ideas",
    "We will have this documented someplace soon.",
    "what do you mean specifically?",
    "what's the result? do you have a bug?",
    "why do you need it?",
    "yeah I thought so",
    "yeah, it is a parameter or something similar",
    "yeah, thats reasonable",
    "yes, but only if we have a justification",
    "you should tell David, he makes the rules :)"
];

Chetan.prototype.ask = function(question) {
    return this.phrases[Math.floor(this.phrases.length*Math.random())];
};
